### ISSUE TITLE
Orientation of taken photo is sometime wrong.

### ISSUE THREAD

**Issue by confile** [tdginternet/TGCameraViewController#19]
I am working on the square branch of your project. As you can see. The orientation of the image is wrong after taking the photo (not from album). This appear nearly 1 out of 10 captures. I do not know why because most of the time the orientation is correct.

![foto 29 11 14 16 19 15](https://cloud.githubusercontent.com/assets/64265/5234905/ac20e174-77e3-11e4-8cfe-845cdb065653.png)

**Comment by Bruno-Furtado** [comment]
@confile,

I made some improvements to the __orientation__ branch.
You could test?

**Comment by confile** [comment]
I will test it today and give you feedback.

**Comment by Bruno-Furtado** [comment]
@confile,
All right?

**Comment by confile** [comment]
I tested the orientation branch I still have the problem when you tap on shot and rotate the device at the same time then the photo gets rotated.

**Comment by chrise86** [comment]
The first time I took a photo the orientation was wrong :-/

**Comment by arpad05** [comment]
can i participate in this project?

**Comment by Bruno-Furtado** [comment]
Of course @yesidi!
Just send a pull request with your changes.
