### ISSUE TITLE
Couldn't Run on Device

### ISSUE THREAD

**Issue by deviggner** [tdginternet/TGCameraViewController#23]
I tried to run the example app on iPad and iPhone (both have iOS 8.1.1). But after i tap the 'Take photo' button, the black screen appears and the camera doesn't start. Any help?

**Comment by Bruno-Furtado** [comment]
@deviggner, 
You could run the example?

If not, try cleaning the project, close Xcode and delete the `DerivedData` directory files.
http://goo.gl/egvDYB

**Comment by nhnam** [comment]
Me too. Could not run on my iphone4s ios 8.1.2

**Comment by Bruno-Furtado** [comment]
@nhnam,

The problem must be related to the XIBs.
You must clear the project and build again.
Have you performed this step?

**Comment by nhnam** [comment]
I solved my issue with this suggestion https://github.com/tdginternet/TGCameraViewController/issues/29

**Comment by lfarah** [comment]
Same here on iOS 9
