### ISSUE TITLE
Cannot get the image without using [TGCamera setOption:kTGCameraOptionSaveImageToAlbum value:[NSNumber numberWithBool:YES]];

### ISSUE THREAD

**Issue by confile** [tdginternet/TGCameraViewController#26]
I created a demo project here (https://github.com/confile/TGCameraViewControllerTest) to show this problem. Only if I set: 

```
[TGCamera setOption:kTGCameraOptionSaveImageToAlbum value:[NSNumber numberWithBool:YES]];
```
in my init method I get the images correctly returned from the TGCameraViewController. Without setting the above line there will be no image returned.

I hope that my sample project helps. You just have to look at BCamera.m. I modified the TGCameraViewController.m and marked the modified parts. The modification is just to skip the screen with the filters after the image has been captured.

Do you have any idea how I get the image captured or retrieved from the album without using the above line?

**Comment by confile** [comment]
@Bruno-Furtado Do you have any idea on this issue?

**Comment by Bruno-Furtado** [comment]
@confile,
I conducted two tests.

1. I took a picture with the camera (http://goo.gl/78dHS8)
2. Selected a photo from album (http://goo.gl/t4Wg0u)

I'm sending you the two prints 
In both you can get the picture.
Sorry but I don't understand your question.

**Comment by confile** [comment]
@Bruno-Furtado You are right I get the Image, i.e. the UIImage on iOS but it is not correctly transferred to the html index page and it is not displayed there. 

As you can see in the last line of both of your outputs the image URI is some strange url starting with: 

```
asset.JPG?id=....
```
This only happens if I don't do 

```
[TGCamera setOption:kTGCameraOptionSaveImageToAlbum value:[NSNumber numberWithBool:YES]];
```

in my init. 

Do you get my point?

**Comment by Bruno-Furtado** [comment]
Do you want to display the image in HTML?

**Comment by confile** [comment]
Yes I want to display the image in HTML. you can see that it works perfect if you enable 

```
[TGCamera setOption:kTGCameraOptionSaveImageToAlbum value:[NSNumber numberWithBool:YES]];
```
in BCamera.m init.

**Comment by Bruno-Furtado** [comment]
@confile,

Some threads in your code are causing problems.
I managed to make the image is displayed by adding a timer, see if this can help:

- - -

__-[BCamera cameraDidSavePhotoAtPath:]__
```obj-c
- (void)cameraDidSavePhotoAtPath:(NSURL *)assetURL
{
    // When this method is implemented, an image will be saved on the user's device
    NSLog(@"%s cameraDidSavePhotoAtPath album path: %@", __PRETTY_FUNCTION__, assetURL);
    
    NSString *imagePath = [assetURL absoluteString];
   // _imagePath = [assetURL absoluteString];
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [NSThread sleepForTimeInterval:1.0f];
        
        dispatch_async(dispatch_get_main_queue(), ^{
            CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:imagePath];
            [self.commandDelegate sendPluginResult:pluginResult callbackId: self.latestCommand.callbackId];
        });
    });
}
```

**Comment by confile** [comment]
@Bruno-Furtado Your code works fine thank you. There is one last problem. If you choose to load an image from album in the camera view it gets saved again. How can I prevent the photo from being resaved when I choose an album photo?

**Comment by Bruno-Furtado** [comment]
@confile,
This is the problem I told you about. 
Unfortunately I have not found a solution.
I believe there is no need to save an image that is already on the album.

**Comment by confile** [comment]
@Bruno-Furtado Yes there is no need to save an image that is already on the album. So how do I prevent the app from doing this?
Thank you for your help.

**Comment by Bruno-Furtado** [comment]
@confile,
Just don't implement the `cameraDidSavePhotoAtPath:` method.
Ok?

**Comment by confile** [comment]
@Bruno-Furtado I delete ``cameraDidSavePhotoAtPath``in BCamera.m but still when I choose an image from album it saves this image again. How can I avoid this? Sorry for my many questions.

**Comment by confile** [comment]
well I solved it thank you.
