### ISSUE TITLE
Change Image Dimensions

### ISSUE THREAD

**Issue by confile** [tdginternet/TGCameraViewController#28]
Is there a way to change the dimension of the image. I always get images of size 640px x 640px. 
Even on iPad I get that small images.

**Comment by confile** [comment]
Sorry I was wrong. The problem is that there is no way to change the dimension.

**Comment by jrr363** [comment]
I changed this method to return the original image?

+ (UIImage *)cropImage:(UIImage *)image withCropSize:(CGSize)cropSize

and i am getting 2448 X 3264 on an iPhone 5

**Comment by jrr363** [comment]
Oh thanks for the awesome work Gostoso!
