### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by chrise86** [tdginternet/TGCameraViewController#30]
How would I (programmatically) change the colours and images? Are there any options?

**Comment by miketsprague** [comment]
If you're still trying to do this, you can use my branch
PR https://github.com/tdginternet/TGCameraViewController/pull/37
or 
https://github.com/miketsprague/TGCameraViewController

**Comment by Bruno-Furtado** [comment]
We are working on this functionality in the [colors](https://github.com/tdginternet/TGCameraViewController/tree/colors) branch.

**Comment by Bruno-Furtado** [comment]
@chrise86,

Option available in version [2.2](https://github.com/tdginternet/TGCameraViewController/releases).
[How to change colors](https://github.com/tdginternet/TGCameraViewController#change-colors).
