### ISSUE TITLE
Black screen after taking pic

### ISSUE THREAD

**Issue by Knights22** [tdginternet/TGCameraViewController#36]
Testing the example app, after taking a pic the screen is just black and no photo is saved to the camera roll. I am using iphone 6.

**Comment by yesidi** [comment]
I have this issue too.

**Comment by Bruno-Furtado** [comment]
Of course @yesidi!
Just send a pull request with your changes.

**Comment by Bruno-Furtado** [comment]
Guys, 
I could not simulate the problem. :(

You could tell in which case occurs?
It's in some specific device? Some version of iOS?

**Comment by Knights22** [comment]
I've tested on iphone 6. It occurs when you take a pic and then segue. What device have you tested it on?

**Comment by Bruno-Furtado** [comment]
I also tested on an iPhone 6 with iOS 8.3.
This failure occurs always or sometimes?

**Comment by Knights22** [comment]
Always, Is it working for you?

**Comment by Bruno-Furtado** [comment]
Yes , I will try to simulate the problem...

**Comment by Knights22** [comment]
I tried out a few months ago on 8.3, but i will download it again and give it a try.

**Comment by lfarah** [comment]
+1

**Comment by lfarah** [comment]
I forgot that I already had this problem and that's how you can fix it: #51
