### ISSUE TITLE
[Feature] Load image too slow from PhotoLibrary 

### ISSUE THREAD

**Issue by tomisacat** [tdginternet/TGCameraViewController#38]
I noticed that you use UIImagePickerController and I test it on my iPhone 5 which contains more than 2000 photos, it's slow to load thumbnail from photo library. Will you write a custom picker controller to take place of system control?

BTW, really thank you for contributing so great work!

**Comment by Bruno-Furtado** [comment]
@tomisacat, thanks for the suggestion!
I added your suggestion to our [Todo](https://github.com/tdginternet/TGCameraViewController#todo) list.
