### ISSUE TITLE
How can i add my localization?

### ISSUE THREAD

**Issue by MattiaConfalonieri** [tdginternet/TGCameraViewController#39]
How can i add my localization at the project?

**Comment by Bruno-Furtado** [comment]
__1. Go to the directory:__
TGCameraViewController / Resources / TGCameraViewController.bundle

---

__2. Create a new folder:__
`it-IT.lproj` (or `fr.lproj`, `es.lproj`, etc.)

---

__3. Create a file within the lproj folder with the following name:__
`Localizable.strings`

---

__4. Add the following parameter values:__

```
/* Take photos */
"TGCameraViewController-Title" = "";

/* Allow access to your camera to start taking pictures with app */
"TGCameraViewController-Subtitle" = "";

/* 1. Open the Settings of your device */
"TGCameraViewController-Step1" = "1. ";

/* 2. Go to Privacy */
"TGCameraViewController-Step2" = "2. ";

/* 3. Go the Camera */
"TGCameraViewController-Step3" = "3. ";

/* 4. Activate */
"TGCameraViewController-Step4" = "4. ";
```

---

__5. Send a pull request for us__
