### ISSUE TITLE
Disable Filters

### ISSUE THREAD

**Issue by Phillip3** [tdginternet/TGCameraViewController#41]
How would I go about disabling the filters after the user takes a photo?

**Comment by Bruno-Furtado** [comment]
This option does not exist, but I think it's a good idea. 
I would be happy if you contribute.

**Comment by Phillip3** [comment]
I created a branch that has a new optional delegate method called cameraFilterViewEnabled. It returns whether or not the wand is displayed that allows photo editing.

return true
![enabled](https://cloud.githubusercontent.com/assets/8754882/8388123/6f2c1b04-1c24-11e5-9e0c-21c0d1ed526d.PNG)

return false
![disabled](https://cloud.githubusercontent.com/assets/8754882/8388124/6f392678-1c24-11e5-89f3-420d231e4c85.PNG)

The default is true so those who are using the project don't have to change anything to keep it working like it is.
