### ISSUE TITLE
Remove "square" cropping

### ISSUE THREAD

**Issue by woobione** [tdginternet/TGCameraViewController#43]
Hi,
I might just be completely stupid but everywhere people are referring to the "square" branch of this project. But I can only see one branch and that one is locked to square size, both when taking a picture and selecting a picture. Is there a branch that can be used as a normal camera?

Thanks in advance!

**Comment by Bruno-Furtado** [comment]
@woobione,
The project was designed to capture square images, but you can change these settings:

[TGCameraViewController - 254](https://github.com/tdginternet/TGCameraViewController/blob/2.2.1/TGCameraViewController/Classes/Control/TGCameraViewController.m#L254)
When calling this method the crop size is set. You can change it to the size you want.

[TGCameraViewController.xib (Optional)](https://github.com/tdginternet/TGCameraViewController/tree/2.2.1/TGCameraViewController/Classes/View/Base.lproj) 
If you wish, change the size of `Capture View`.

**Comment by woobione** [comment]
@Bruno-Furtado Thank's for the help! I will make a fork of this project (probably tomorrow) [here](https://github.com/DicomExpense/TGCameraViewController) that will instead take regular sized pictures if anyone else asks for this ability. Would also like to thank you for a great project and let you know that we will use it in our application :)

**Comment by woobione** [comment]
I have a fork of this project here that can be used if anyone wants to use normal sized images: https://github.com/DicomExpense/TGCameraViewController

To get through pod use:
```
pod 'TGCameraViewController', :git => 'https://github.com/DicomExpense/TGCameraViewController.git'
```

**Comment by swabzz** [comment]
@woobione, your solution is not working. when i launching cameraviewcontroller it showing nothing but a blank window with black color background.

**Comment by woobione** [comment]
@swabzz We actually use the exact version above in our project with 20k+ users every day and it works just fine for us. However, I haven't updated the code to match the latest version and haven't touched anything of the branch in over a year so there is a big chance it's no longer compliant with the new SDK. Since we are making a new major version of our app which will not use this controller I will most likely not fix it either. Feel free to make your own branch and do the adjustments mentioned by @Bruno-Furtado above. Good luck!

**Comment by swabzz** [comment]
@woobione thanks for quick reply.

Actually i am using this library to capture two different size images with different aspect ratio in my application. can you suggest me what change i should make here please?

**Comment by woobione** [comment]
@swabzz As I haven't looked at the code since the new changes I don't know if it still works the same. But see @Bruno-Furtado 's answer above. You have to change the capture view to support full screen live view instead of square live view if that's something you want. Then you also have to change the cropping-function to not crop. Then you can do the final cropping in your app code instead of in the camera controller. Best of luck.
