### ISSUE TITLE
use_frameworks! broke camera

### ISSUE THREAD

**Issue by Phillip3** [tdginternet/TGCameraViewController#45]
I recently had to start using frameworks for cocoa pods, but when I added the use_frameworks! keyword to the Podfile, the camera now just shows a black screen with no errors or warnings. I tried making sure the project was set to build for iPhone instead of general (a fix for a similar issue), but to no avail.

**Comment by Phillip3** [comment]
I created a blank project with a single view controller:
```swift
import UIKit
import TGCameraViewController

class ViewController: UIViewController, TGCameraDelegate {
  
  @IBAction func bringUpCamera(sender: AnyObject) {
    let navController = TGCameraNavigationController.newWithCameraDelegate(self)
    presentViewController(navController, animated: true, completion: nil)
  }
  func cameraDidCancel() {
    //camera cancelled
  }
  func cameraDidTakePhoto(image: UIImage!) {
    //do something
  }
  func cameraDidSelectAlbumPhoto(image: UIImage!) {
    //do something
  }
}
```
Here is my Podfile:
```ruby
platform :ios, '8.0'
target 'Test_TGCamera' do
  use_frameworks!
  pod 'TGCameraViewController', '~>2.2.1'
end
```
When you hit the button that executes the bringUpCamera() function, you get a black screen with no errors or warnings. It does not go away with time, and changing the device of the project target does not help.

**Comment by nathankot** [comment]
this is happening to me too

**Comment by kenancasey** [comment]
I have this same issue.

**Comment by acidfilez** [comment]
The same issue, To Use I had to remove it from the pods, insert it manually in the project.

In the Header Bridge:
´´´
#import "TGCameraViewController.h"
´´´

**Comment by Phillip3** [comment]
I did that as well @acidfilez. Thanks for posting the work around.

**Comment by Alexgao11** [comment]
What if I want to use_frameworks! for other dependencies?

**Comment by Remyoman** [comment]
Experiencing the same issue. I set the use_frameworks! flag for all my projects and also use the module import statement. This means I can't simply not use frameworks. 

Manually importing is a workaround, but this indicates there might be a problem with the podspec.

**Comment by macecchi** [comment]
I'm working on a new release right now and I'll check what's going on. Thanks!

**Comment by macecchi** [comment]
I tested it with version 2.2.3 and it seems to have fixed it. Could you try updating the pod to the latest version and see if that's fixed?

(Just to make sure: if you use `use_frameworks!` you have to add the headers to the Bridging File and also `import TGCameraViewController`.)

**Comment by Remyoman** [comment]
@macecchi The new podspec isn't pushed to the master repo.

I tried it by installing it through the 2.2.3 tag, but it still comes up with a black screen on my device. The library is used with
```
@import TGCameraViewController

TGCameraNavigationController *navigationController = [TGCameraNavigationController newWithCameraDelegate:self];
[self presentViewController:navigationController animated:YES completion:nil];
```
I also noticed the TGCameraFunctions.h can create duplicate symbols because it isn't guarded.

**Comment by macecchi** [comment]
Thanks @Remyoman. I was able to reproduce it here. 

I think the podspec is pushed. I just ran `pod updated` from a project and it detected the latest version. Did you update your repo? `pod repo update`

**Comment by macecchi** [comment]
@Remyoman I just pushed a new version - 2.2.4 - which I believe that fixes it! Could you try it and tell me if it works?? :)

**Comment by Remyoman** [comment]
@macecchi Yes, it works for me now. Thanks for the fast fix!

**Comment by macecchi** [comment]
Yay! 🎉
