### ISSUE TITLE
Changing the colors / images of the buttons?

### ISSUE THREAD

**Issue by MattFedo** [tdginternet/TGCameraViewController#46]
How can I change the icons and colors of the buttons?

I changed the xcassets, but it does not seem to do anything.

Thanks!

**Comment by Bruno-Furtado** [comment]
@MattFedo,

See if this can help you...
https://github.com/tdginternet/TGCameraViewController#change-colors

**Comment by MattFedo** [comment]
Dang, didn't even see that down there.  Thanks!!
