### ISSUE TITLE
Black Screen on presenting TGCameraViewController

### ISSUE THREAD

**Issue by lfarah** [tdginternet/TGCameraViewController#51]
I had TGCameraViewController installed by CocoaPods and when I was presenting TGCameraViewController, it is showing me a black screen

**Comment by lfarah** [comment]
Works when downloading TGCameraViewController classes without cocoapods

**Comment by ingouackaz** [comment]
The problem comes from bundle ressources.

If you want to use cocoapods, you have tu to copy paste all resources of TGCameraViewController in your local bundle
