### ISSUE TITLE
Slow opening camera, take picture lag

### ISSUE THREAD

**Issue by canaksoy** [tdginternet/TGCameraViewController#53]
There is a small init waiting when opening camera view.
Also after taking a photo with a little hand movement makes taken photo blury.
Can you make any improvements about it?

iOS 8.4 - iPhone6 Plus.

**Comment by deada92** [comment]
+1 

iOS 9.3 - iPhone 5s

**Comment by macecchi** [comment]
A few performance improvements have been made in version [2.2.3](https://github.com/tdginternet/TGCameraViewController/releases/tag/2.2.3). Can you see if that helps?
