### ISSUE TITLE
Experiencing crash on imageFromContext: method on iOS 9 

### ISSUE THREAD

**Issue by kunwarh** [tdginternet/TGCameraViewController#56]
Everything works fine on iOS 8 but on updating to iOS 9 i get a crash on line
 "CGImageRef imageRef = [context createCGImage:outputImage fromRect:extent];"
 I think it has something to do with CIContext but not able to figure what it is. Any help would be highly appreciated.

**Comment by macecchi** [comment]
I'm closing this issue due to the lack of activity and further debug information. If this issue still persists in the latest version of the pod, please tell us :)
