### ISSUE TITLE
Photo Album button disappear when not run in debug mode

### ISSUE THREAD

**Issue by coderwsli** [tdginternet/TGCameraViewController#64]
![img-20160411-wa0012](https://cloud.githubusercontent.com/assets/7858565/14430640/fa23b858-0034-11e6-9341-83fba86fa84d.jpg)

Any advice?

**Comment by zebganzo** [comment]
up

**Comment by ZhipengApv** [comment]
same problem on iOS 9.3.3

**Comment by macecchi** [comment]
Thanks for reporting. I'm working on an fix for it right now!

**Comment by macecchi** [comment]
I pushed version 2.2.3 now. Could you try updating the pod and see if it fixed that issue?

**Comment by macecchi** [comment]
I'll close this for now but please don't hesitate do post if you still have that issue :)

**Comment by yao23** [comment]
@macecchi v2.2.7 fixes the missing album button!

**Comment by yao23** [comment]
But it hides status bar after show camera page, the following code will show it again:

    [self setNeedsStatusBarAppearanceUpdate];
    self.navigationController.navigationBar.barStyle = UIBarStyleBlack;
    self.navigationController.navigationBar.translucent = NO;
