### ISSUE TITLE
Selected Photo from Library Appears to be Out of Bounds

### ISSUE THREAD

**Issue by allanmacatingrao** [tdginternet/TGCameraViewController#70]
I have tried loading image from Photo Library but the layout of the selected image is out of bounds.

This is when selecting the image from the album:
![img_4102](https://cloud.githubusercontent.com/assets/4327024/17238112/6d29d430-558b-11e6-9a13-74834630bddb.PNG)

This is the view after selecting the image:
![img_4103](https://cloud.githubusercontent.com/assets/4327024/17238115/6fbea41e-558b-11e6-89ae-706a4c05a5e1.PNG)

**Comment by macecchi** [comment]
Thanks for reporting this. This is happening because UIImagePickerController is being presented as a fullscreen modal when it's supposed to be presented with a popover. I'm working on a fix right now.
