### ISSUE TITLE
BackgroundColor of the big Circle

### ISSUE THREAD

**Issue by Stan92** [tdginternet/TGCameraViewController#72]
Hi again..
Just a quick question. Is it possible to change the background color of the "Validation" circle or the color of the "Validation Mark"?
When I set the tint color to white..  both come with White color.
And btw, my status bar disappears when I tap onto the button that launches the TGCameraNavigationController. How to avoid this?

And last but not least.. I thank you :-) for sharing this library.

**Comment by macecchi** [comment]
No, you can't change the checkmark's color for now. It's always set as white :/
I'll add another option to set a different color on a future release.

About the status bar, it should reappear after you dismiss the camera controller, not affecting your app.
