### ISSUE TITLE
Features to improve

### ISSUE THREAD

**Issue by yao23** [tdginternet/TGCameraViewController#73]
1. All camera photos are very unclear and fuzzy
2. Doesn't focus clearly on the item
3. Camera takes a while to focus

**Comment by macecchi** [comment]
Could you share more details or screenshots? Why do you think the photos are unclear/fuzzy?
Thanks!

**Comment by yao23** [comment]
I updated to v2.2.7 and it's better for image quality now.

Did you improve the speed to focus?

**Comment by macecchi** [comment]
I haven't changed anything related to that on the latest versions. What version were you using before? Can I close this issue?

**Comment by yao23** [comment]
OK, I will close it. Please keep improving the speed to focus and quality of photos.
