### ISSUE TITLE
Custom rectangular shape crop

### ISSUE THREAD

**Issue by swabzz** [tdginternet/TGCameraViewController#74]
Hi!
Is there any option to make the cropper to take a custom rectangular shape, rather than a simple square?

**Comment by macecchi** [comment]
No :/
As this will not be implemented any time soon, I will be closing this issue. If anyone wants to contribute to this, please submit a PR :)

**Comment by swabzz** [comment]
Can you please suggest how should i find solution for this??

**Comment by swabzz** [comment]
I am still waiting for this feature in library??
any update on that please?

**Comment by macecchi** [comment]
Hi @swabzz. I'm working on this feature right now.

How do you expect this to work? As the default (by setting that in code in the TGCamera options) or as an option to the user?

**Comment by swabzz** [comment]
Yes as an option to the user in TGCameraViewController? 
Passing height & width as a parameters would be best :-)

**Comment by swabzz** [comment]
Are you working on this???

**Comment by macecchi** [comment]
@swabzz Yes, but I'm implementing as a boolean option to either use a square size or the original size. Is there any reason you prefer defining the width & height manually?

**Comment by macecchi** [comment]
I've added an option to disable cropping. Does that work for you? You can test it in [this](https://github.com/tdginternet/TGCameraViewController/tree/feature/standard-image-aspect) branch.

**Comment by swabzz** [comment]
@macecchi, no disabling the crop not working for me, I am using library to crop image in two different aspect ratio in same project.

**Comment by macecchi** [comment]
@swabzz Do you mean the option is not working or it does not fit your needs?

**Comment by swabzz** [comment]
thanks for help buddy but It does not fit to my need. 
I need to user same library in same project with 2 different aspect ration.
i mean parameterised tg instance.

**Comment by macecchi** [comment]
I see. So you need to get the same photo in two different aspect ratios? In that case it makes more sense to get the original photo from the library and then crop manually, as it is a very specific use case. 

If you sometimes want to take a square photo and sometimes the original photo, you can change the TGOption before each.

**Comment by swabzz** [comment]
Hello @macecchi 

I am not using same photo in different aspect ratio but different photos on different view-controllers in different aspect ratio. 

so i want to use library to get and crop different images in different aspect ratios.

Ex -- On one page I want profile image in 2:2 aspect ratio and on other page i want to take featured image in 2:3 aspect ratio.

Thanks in advance buddy :-)

**Comment by macecchi** [comment]
I get it now. You can just set the TGOption with the original or square aspect right before calling TGCameraViewController in each of your view controllers. I think that would work for you.

**Comment by swabzz** [comment]
Thanks @macecchi but didn't get you.
can you please show me any example for how to use different crop aspect ration on different view controllers??

**Comment by macecchi** [comment]
Assuming you are in your view controller 1, where you use the square aspect ratio, you call TGCameraViewController like this:

```obj-c
[TGCamera kTGCameraOptionUseOriginalAspect value:@NO]; // NO forces it to use the square aspect
TGCameraNavigationController *navigationController = [TGCameraNavigationController newWithCameraDelegate:self];
[self presentViewController:navigationController animated:YES completion:nil];
```

And then, on your view controller 2, where you want the 2:3 aspect ratio, you'd call the library like this:


```obj-c
[TGCamera kTGCameraOptionUseOriginalAspect value:@YES]; // YES makes it use the original (2:3) aspect ratio
TGCameraNavigationController *navigationController = [TGCameraNavigationController newWithCameraDelegate:self];
[self presentViewController:navigationController animated:YES completion:nil];
```

This is assuming you are configuring your Podfile to use the branch `feature/standard-image-aspect` instead of the release. I haven't tested everything on this branch yet so it's not ready to be released as a new version yet.

**Comment by swabzz** [comment]
Thanks @macecchi 
I will try it and let you know

**Comment by swabzz** [comment]
@macecchi 

Where are you defining the variable for aspect ration (2:3) ?

Do i need to define it anywhere in code? 

Sorry for silly questions but i am confused about its working :-) Hope you understand

**Comment by macecchi** [comment]
```obj-c
[TGCamera kTGCameraOptionUseOriginalAspect value:@YES];
```

**Comment by swabzz** [comment]
Thanks @macecchi 

@macecchi what if i need to use cropping aspect ratio to 3:2 ?

Do i have any option to ser cropping parameter anywhere?

**Comment by macecchi** [comment]
@swabzz The option above enables the original aspect ratio of the camera, which is 2:3 / 3:2 already. You don't need to crop it.

**Comment by swabzz** [comment]
Okay Let me give a try

**Comment by macecchi** [comment]
@swabzz Could you get it working? Do you have any feedback?

**Comment by swabzz** [comment]
No
Its not working yet as i was expecting

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by macecchi** [comment]
@swabzz Could you give any more details? What is happening and what is the expected behaviour?

**Comment by swabzz** [comment]
Hi,

Thanks for replying sir.

In my app i need 2 buttons on same page to get images as
(1) - Profile image (1X1) and
(2) - Background image (3:1)

Thanks.
Shoaib Bagwan



________________________________

**Comment by macecchi** [comment]
1) The 1:1 format is the standard one. 
2) Earlier you said you needed 3:2 format, which is possible with the current implementation. 3:1 is a very specific format so it makes no sense to include it as an option. However, you can easily get a photo with the original aspect and then crop programatically.

I'll be closing this issue as I think we have reached what was purposed in the beginning of this thread. The feature branch will be merged in master and I'll release a new version soon.

**Comment by serjooo** [comment]
How about making the camera more customizable by making that square cropper resizable by dragging the sides and then before initializing the camera you would set a boolean if you want to use that feature or not
