### ISSUE TITLE
TGCameraViewController is not compatible with iOS 7. Please bump up the iOS version in podspec

### ISSUE THREAD

**Issue by abbasmousavi** [tdginternet/TGCameraViewController#76]
TGCameraViewController uses ```imageNamed:inBundle:compatibleWithTraitCollection:```  in many places. it is iOS 8+ API

**Comment by macecchi** [comment]
Thanks @abbasmousavi. I just pushed this fix in [v2.2.7](https://github.com/tdginternet/TGCameraViewController/releases/tag/2.2.7).
