### ISSUE TITLE
Crashing when a picture is taken 

### ISSUE THREAD

**Issue by jackpaster** [tdginternet/TGCameraViewController#87]
@confile @adamtootle @psobot @ruanltbg @kindraywind Hello, First of all this is an amazing project. But theres one problem. I'm using this camera view in my settings page and when a user clicks on the profile image, this camera pops up and when an image is taken the picture taken will be the users new profile image. The only problem is that this project works fine if the settings view controller is the initial view controller. But If my main page is the main view controller and I present the setting page and then click on the profile image to take a photo(then the tgcameraview comes up). Once I click on the camera button or try to access my photos, the app crashes. If you need a video to explain further, I will send it to you. But this is very weird and it might be a bug in your code.

**Comment by macecchi** [comment]
Hi @jackpaster. Could you attach a crash report with the stack trace of the crash? This is the only way I can investigate the issue.

**Comment by macecchi** [comment]
Closing the issue due to lack of more info. If you still need help, please reopen it and attach more relevant information so I can debug it :)
