### ISSUE TITLE
how to implement Burst effect.

### ISSUE THREAD

**Issue by ajay2c9** [tdginternet/TGCameraViewController#90]
Hi, I want to implement the burst effect by using this pod. Is there any possibility to implement this effect.
Thank you

**Comment by macecchi** [comment]
Hi @ajay2c9. Could you be more specific about what you mean by "burst effect"? What would be the use case for this?

**Comment by ajay2c9** [comment]
We can take continuous images in iPhone (Process: open camera--> Press vol+) it will take continuous images.This effect is burst effect. Is there ay possibility to implement this effect.

**Comment by macecchi** [comment]
Oh, right.

Sorry, but there is no way to implement this feature now. 😕

I'm going to close this issue as this is not going to be implemented.
